import{a as g,S as L,i as u}from"./assets/vendor-b11e2a50.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const v="45139433-b39febc8ea292e87313288c36",w="https://pixabay.com/api/";async function h(r,t=1,o=15){return(await g.get(`${w}`,{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:o}})).data}function f(r,t){const o=r.hits.map(e=>`
      <li>
        <a class="gallery-link" href=${e.largeImageURL}>
          <img src="${e.webformatURL}" alt="${e.tags}">
          <div>
            <p><span>Likes</span>${e.likes}</p>
            <p><span>Views</span>${e.views}</p>
            <p><span>Comments</span>${e.comments}</p>
            <p><span>Downloads</span>${e.downloads}</p>
          </div>
        </a>
      </li>`).join("");t.insertAdjacentHTML("beforeend",o),new L(".gallery a",{captData:"alt",capDelay:250}).refresh()}const m=document.querySelector(".form"),b=document.querySelector(".input"),p=document.querySelector(".gallery"),i=document.querySelector(".loader"),c=document.querySelector(".load-more");let l,n=1,S=15,y=0;function q(r){if(c.classList.add("visually-hidden"),r.preventDefault(),p.innerHTML="",i.classList.remove("visually-hidden"),l=b.value.trim(),l===""){i.classList.add("visually-hidden");return}n=1,h(l,n).then(t=>{y=Math.ceil(t.totalHits/S),i.classList.add("visually-hidden"),t.hits.length===0?u.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}):(i.classList.add("visually-hidden"),c.classList.remove("visually-hidden"),f(t,p))}).catch(t=>{u.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:"Request feiled. Please try again"}),i.classList.add("visually-hidden")}),m.reset()}async function P(r){if(n+=1,n>y)return c.classList.add("visually-hidden"),u.error({position:"topRight",message:"We're sorry, there are no more posts to load"});const t=await h(l,n);f(t,p);const a=document.querySelector(".gallery li").getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}m.addEventListener("submit",q);c.addEventListener("click",P);
//# sourceMappingURL=commonHelpers.js.map
