import{a as g,S as L,i as p}from"./assets/vendor-BjmtRwYh.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const v="45139433-b39febc8ea292e87313288c36",b="https://pixabay.com/api/";async function m(s,t=1){const o=new URLSearchParams({key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t});try{return(await g.get(`${b}?${o}`)).data}catch{return{error:"Network response was not ok"}}}function y(s,t){const o=s.hits.map(e=>`
      <li>
        <a class="gallery-link" href=${e.largeImageURL}>
          <img src="${e.webformatURL}" alt="${e.tags}">
          <div>
            <p><span>Likes</span>${e.likes}</p>
            <p><span>Views</span>${e.views}</p>
            <p><span>Comments</span>${e.comments}</p>
            <p><span>Downloads</span>${e.downloads}</p>
          </div>
        </a>
      </li>`).join("");t.insertAdjacentHTML("beforeend",o),new L(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const f=document.querySelector(".form"),w=document.querySelector(".input"),n=document.querySelector(".gallery"),a=document.querySelector(".loader"),c=document.querySelector(".more-button");let d=1,l="",h=0;async function S(s){if(s.preventDefault(),n.innerHTML="",c.classList.add("visually-hidden"),a.classList.remove("visually-hidden"),l=w.value.trim(),d=1,l===""){a.classList.add("visually-hidden");return}try{const t=await m(l,d);a.classList.add("visually-hidden"),t.hits.length===0?p.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}):(h=t.totalHits,y(t,n),n.children.length<h&&c.classList.remove("visually-hidden"))}catch(t){console.error(t),a.classList.add("visually-hidden")}f.reset()}async function q(){a.classList.remove("visually-hidden"),d+=1;try{const s=await m(l,d);a.classList.add("visually-hidden"),y(s,n);const o=document.querySelector(".gallery li").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"}),n.children.length>=h&&(c.classList.add("visually-hidden"),p.info({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"blue",message:"We're sorry, but you've reached the end of search results."}))}catch(s){console.error(s),a.classList.add("visually-hidden")}}f.addEventListener("submit",S);c.addEventListener("click",q);
//# sourceMappingURL=commonHelpers.js.map
